version: "3"

services:
    db:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        volumes:
            - "db_app:/var/lib/postgresql/data:rw"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        ports:
            - "5432:5432"
        networks:
            - symfony_app


    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - db
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
